export enum QueryKeys {
  Attributes = 'attributes',
  ShippingInfo = 'shipping-info',
  GalleryItems = 'gallery-items',
  Categories = 'categories',
  Category = 'category',
  Products = 'products',
  Product = 'product',
  ProductVariants = 'productVariants',
  Galleries = 'galleries',
  Comments = 'comments',
  Blog = 'blog',
  Blogs = 'blogs',
  Tags = 'tags',
  Tag = 'tag',
  Orders = 'orders',
  Shippings = 'shippings',
  Pages = 'pages',
  Page = 'page',
  Contacts = 'contacts',
  Banners = 'banners',
  Users = 'users',
  Fonts = 'fonts',

  BulkPricing = 'bulkPricing',
  BulkPricings = 'bulkPricings'
}
