export enum QueryKeys {
  Attributes = 'attributes',
  ShippingInfo = 'shipping-info',
  GalleryItems = 'gallery-items',
  Categories = 'categories',
  Products = 'products',
  Product = 'product',
  ProductVariants = 'productVariants',
  Galleries = 'galleries',
  Comments = 'comments',
  Blog = 'blog',
  Blogs = 'blogs',
  Tags = 'tags',
  Orders = 'orders',
  Shippings = 'shippings',
  Pages = 'pages',
  Contacts = 'contacts',
  Banners = 'banners',
  Users = 'users'
}
